### ISSUE TITLE
How to convert the filter_scale to  the geographic distance

### ISSUE THREAD

**Issue by liu-ran** [oceanhackweek/ohw22-proj-gcmfilters#14]
Hi, I see your beautiful work about filtering the eddy flow through the gcm_filter package. But I have a question here. The filter_scale only represents severel grid points. How to explain the filter_scale as the precise scale in unit of kilometers?

**Comment by NoraLoose** [comment]
Thanks for reaching out @liu-ran! The gcm-filters documentation describes examples for (i) fixed factor filtering (what we do here), and (ii) fixed filter scale filtering (what you may want to do?), see for example [this notebook](https://gcm-filters.readthedocs.io/en/latest/examples/example_filter_types.html). Please let us know if this answers your question!

**Comment by liu-ran** [comment]
Hi @NoraLoose , many thanks for your help and useful information!
