### ISSUE TITLE
Merge the B-grid vector Laplacian into GCM-filters

### ISSUE THREAD

**Issue by paigem** [oceanhackweek/ohw22-proj-gcmfilters#4]
@NoraLoose and I will tie up loose ends and get [this PR](https://github.com/ocean-eddy-cpt/gcm-filters/pull/128) merged so we can use it in our project!

**Comment by NoraLoose** [comment]
@paigem I left some comments on [the PR](https://github.com/ocean-eddy-cpt/gcm-filters/pull/128). I think we may be close!

**Comment by paigem** [comment]
Update: @NoraLoose and I coded up some of the tests needed to merge the PR. We will see if all the tests pass with our updates! 😄

**Comment by NoraLoose** [comment]
They pass! :tada: Next step: Merge [this](https://github.com/paigem/gcm-filters/pull/1) - we are pretty close!

**Comment by paigem** [comment]
DONE!! ✅
